# ApiGatewayRestApi:
#   Type: AWS::ApiGateway::RestApi
#   Properties:
#     ApiKeySourceType: HEADER
#     Description: An API Gateway with a Lambda Integration
#     EndpointConfiguration:
#       Types:
#         - EDGE
#     Name: cs493RestfulAPI
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # AccessControl: PublicRead
      BucketName: !Sub ${self:service}-${self:provider.stage}-${AWS::AccountId}
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
                  
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadGetObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - !GetAtt S3Bucket.Arn
                - '/*'
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content

  # myDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #       - DomainName: !Ref RestfulAPIBucket
  #         Id: myS3Origin
  #         S3OriginConfig:
  #           OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
  #       Enabled: 'true'
  #       DefaultRootObject: index.html
  #       Logging:
  #         IncludeCookies: 'false'
  #         Bucket: mylogs.s3.amazonaws.com
  #         Prefix: myprefix
  #       Aliases:
  #       - mysite.example.com
  #       - yoursite.example.com
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #         - DELETE
  #         - GET
  #         - HEAD
  #         - OPTIONS
  #         - PATCH
  #         - POST
  #         - PUT
  #         TargetOriginId: myS3Origin
  #         ForwardedValues:
  #           QueryString: 'false'
  #           Cookies:
  #             Forward: none
  #         TrustedSigners:
  #         - 1234567890EX
  #         - 1234567891EX
  #         ViewerProtocolPolicy: allow-all
  #       PriceClass: PriceClass_200
  #       Restrictions:
  #         GeoRestriction:
  #           RestrictionType: whitelist
  #           Locations:
  #           - AQ
  #           - CV
  #       ViewerCertificate:
  #         CloudFrontDefaultCertificate: 'true'