# ApiGatewayRestApi:
#   Type: AWS::ApiGateway::RestApi
#   Properties:
#     ApiKeySourceType: HEADER
#     Description: An API Gateway with a Lambda Integration
#     EndpointConfiguration:
#       Types:
#         - EDGE
#     Name: cs493RestfulAPI
Resources:
  RestfulAPIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${self:service}-static-site
      # AccessControl: PublicRead
      # WebsiteConfiguration:
      #   IndexDocument: index.html
  RestfulAPIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: RestfulAPIBucket
    Properties:
      Bucket: !Ref RestfulAPIBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: "Allow"
            Principal: "*"
            Action: ["s3:GetObject","s3:PutBucketPolicy"]
            Resource: !Sub arn:aws:s3:::${self:service}-static-site/*

  # myDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #       - DomainName: !Ref RestfulAPIBucket
  #         Id: myS3Origin
  #         S3OriginConfig:
  #           OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
  #       Enabled: 'true'
  #       DefaultRootObject: index.html
  #       Logging:
  #         IncludeCookies: 'false'
  #         Bucket: mylogs.s3.amazonaws.com
  #         Prefix: myprefix
  #       Aliases:
  #       - mysite.example.com
  #       - yoursite.example.com
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #         - DELETE
  #         - GET
  #         - HEAD
  #         - OPTIONS
  #         - PATCH
  #         - POST
  #         - PUT
  #         TargetOriginId: myS3Origin
  #         ForwardedValues:
  #           QueryString: 'false'
  #           Cookies:
  #             Forward: none
  #         TrustedSigners:
  #         - 1234567890EX
  #         - 1234567891EX
  #         ViewerProtocolPolicy: allow-all
  #       PriceClass: PriceClass_200
  #       Restrictions:
  #         GeoRestriction:
  #           RestrictionType: whitelist
  #           Locations:
  #           - AQ
  #           - CV
  #       ViewerCertificate:
  #         CloudFrontDefaultCertificate: 'true'