Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      AccountRecoverySetting: 
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes: 
        - email
      EmailConfiguration: 
        EmailSendingAccount: COGNITO_DEFAULT
      MfaConfiguration: OFF
      UsernameConfiguration: 
        CaseSensitive: true
      UserPoolName: !Sub ${self:service}-${self:provider.stage}-${AWS::AccountId}

  MyAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: !Sub ${self:service}-${self:provider.stage}-${AWS::AccountId}
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: zx99y1s10k
      ProviderARNs:
        - !GetAtt UserPool.Arn